[tools]
claude = "latest"
gemini = "latest"
jq = "latest"
neovim = "latest"
node = "latest"
pandoc = "latest"
tmux = "latest"

[tasks.restart-alsa]
description = "Restart ALSA to fix the audio output issue"
run = "sudo alsa force-reload"

[tasks.kill-Kindle]
description = "kill all process about Kindle to restart Kindle"
run = "pkill -f Kindle"

[tasks.random-mac]
description = "change to random MAC"
run = """
NIC=$(ls /sys/class/net/ | grep 'wl.*0')
sudo ip link set dev "$NIC" down
sudo macchanger -r "$NIC"
sudo ip link set dev "$NIC" up
"""

[tasks.nix-gc]
description = "Run nix-collect-garbage and optimise the nix store"
run = """
nix-collect-garbage
nix store optimise
"""

[tasks.clean-disk]
description = "Reduce journal logs to 500MB and remove disabled snap revisions"
run = """
sudo journalctl --vacuum-size=500M
snap list --all | awk '/disabled/{print $1, $3}' | while read name rev; do sudo snap remove "$name" --revision="$rev"; done
"""

[settings]
idiomatic_version_file_enable_tools = []
